version: '3.8'

services:
  backend:
    build:
      context: ../../
      dockerfile: module5/deployment/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/trading_platform
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: postgres:13
    container_name: trading_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=trading_platform
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
